# Generated by Django 4.2.2 on 2023-09-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_alter_playlist_description_alter_playlist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo_list.product')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Процент скидки')),
                ('is_limited_edition', models.BooleanField(default=False, verbose_name='Ограниченное издание')),
                ('premium_packaging', models.BooleanField(default=False, verbose_name='Премиальная упаковка')),
            ],
            options={
                'abstract': False,
            },
            bases=('todo_list.product',),
        ),
    ]
