# Generated by Django 4.2.2 on 2023-09-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_song_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=100, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
