# Generated by Django 4.2.2 on 2023-09-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_alter_song_artist_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlist', to='todo_list.song', verbose_name='Песни'),
        ),
    ]
