# Generated by Django 4.2.2 on 2023-09-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0012_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='rendered_content',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
