# Generated by Django 4.2.2 on 2023-10-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0013_sending_rendered_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/image', verbose_name='Изображение'),
        ),
    ]
