# Generated by Django 4.2.2 on 2023-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0014_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks_files/', verbose_name='Загрузка файла'),
        ),
    ]
